/**
 * @file Contains the action constants.
 */
export const DASHBOARD_HEADER = `<!--
This dashboard was generated by the [pauby/top-votes-action](https://github.com/pauby/top-votes-action) action.
-->

A simple dashboard that lists the top issues/bugs/features and pull requests.`
export const DASHBOARD_FOOTER = `> Created by the [pauby/top-votes-action](https://github.com/pauby/top-votes-action) action (last update: ${new Date().toLocaleString()}).`
